### ISSUE TITLE
Allowing go_store shortcode to be enclosing

### ISSUE THREAD

**Issue by alonsofedz** [TheMacLab/game-on#149]
Changing lines 43:44 of the store-shortcode.php to read:

`if (!$content) {`
`     $the_title = get_the_title( $atts['id'] );`
`     return "<a class='go_str_item' onclick='go_lb_opener( {$atts['id']} );'>{$the_title}</a>";`
`} else {`
`     return "<a class='go_str_item' onclick='go_lb_opener( {$atts['id']} );'>{$content}</a>";`
`}`

Would allow us to use the go_store shortcode as an enclosing tag and have clickable images or random passages of text that direct students to the store item.

**Comment by foresthoffman** [comment]
I believe you are correct @alonsofedz. Thanks for the request. I'll add it to the current milestone.

**Comment by foresthoffman** [comment]
Upon further inspection, I discovered that changing those lines was not the simple solution. Allowing the `go_store` shortcode to be used in block format was destructive. The shortcode parser expects a 1:1 relationship between opening and closing shortcode tags. Leaving one tag open eats the next open tag and leaves the next closing tag without an opening tag, and so on.

Consider the following, with a category of "store-items" containing 4 items (ids of 12, 34, 59, and 65).
```bash
[go_store cats="store-items"]
Some content...
[go_store id="65"][/go_store]
```

Humans would expect that to be parsed and output as:
> Store Items
> [Store Item 12](#)
> [Store Item 34](#)
> [Store Item 59](#)
> [Store Item 65](#)
>
> Some content...
> 
> [Store Item 65](#)

What WordPress actually outputs:
> Store Items
> [Store Item 12](#)
> [Store Item 34](#)
> [Store Item 59](#)
> [Store Item 65](#)

This is because the following is considered the content of the first `go_store` tag, which is passing along the "cats" attribute, which is not configured to handle the content within the tags. Thus, nothing but the item list is output.
```bash
Some content...
[go_store id="65"]
```
I hope that makes sense.

---

For backwards compatibility, I've left the `go_store` shortcode functionality as is. Therefore, it was necessary that I create a separate shortcode just for wrapping custom content within the link for a specific Store Item.

So, we now have the `go_store_wrap` shortcode, which takes an "id" attribute, much like `go_store`. However, unlike `go_store` this shortcode cannot be used _without_ the block format.

i.e. The following will not produce any output.
```bash
[go_store_wrap id="65"]
```

But, this will.
```bash
[go_store_wrap id="65"]
Some text or an image<br/><img href="https://avatars2.githubusercontent.com/u/5571660?v=4&s=400"/>
[/go_store_wrap]
```

> [Some text or an image
> ![img](https://avatars2.githubusercontent.com/u/5571660?v=4&s=400)](#)
