### ISSUE TITLE
Time filter only affects stage 3 rewards

### ISSUE THREAD

**Issue by foresthoffman** [TheMacLab/game-on#159]
From AEE:

> Not sure if this is a separate or similar issue but, when I set a time modifier in the advanced settings at the top of the quest the modifier only affect the stage 3 loot after time runs out (a problem since the majority of my loot comes from stage 4.)

According to this, the time filter modifier (which one it is, is unknown) is only affecting the third stage.

**Comment by skocko** [comment]
Tested in student account in Firefox:

t45
Rewards
Stage 1 - 10 Experience 10 Gold
Stage 2 - 10 Experience 10 Gold
Stage 3 - 10 Experience 10 Gold
Stage 4 - 10 Experience 10 Gold

by Boss | Aug 28, 2017
Time Sensitive Quest:
After accepting you will have 60 seconds to reach Stage 3 of this quest before the rewards will be irrevocably reduced by 50%.

----

There used to be a timer countdown. Clicked Stage 2 and nothing happened. Waited a couple of minutes and clicked through. Got 100% rewards.

Tried it again with 1 Minute rather than 60 seconds. Got 100% rewards after waiting 3 minutes between stage 2 and 3.

??!
